<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BMANCHADA-IND" failures="0" tests="4" name="SeleniumPractice.SeleniumFrameworkDesign.StandAloneTest2" time="49.508" errors="1" timestamp="2024-01-10T09:01:25 IST" skipped="1">
  <testcase classname="SeleniumPractice.SeleniumFrameworkDesign.StandAloneTest2" name="submitOrder" time="28.249"/>
  <testcase classname="SeleniumPractice.SeleniumFrameworkDesign.StandAloneTest2" name="OrderHistoryTest" time="2.556">
    <error message="Unresolved compilation problem: 
	productName cannot be resolved to a variable
" type="java.lang.Error">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
productName cannot be resolved to a variable

at SeleniumPractice.SeleniumFrameworkDesign.StandAloneTest2.OrderHistoryTest(StandAloneTest2.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- OrderHistoryTest -->
  <testcase classname="SeleniumPractice.SeleniumFrameworkDesign.StandAloneTest2" name="submitOrder" time="16.917"/>
  <testcase classname="SeleniumPractice.SeleniumFrameworkDesign.StandAloneTest2" name="OrderHistoryTest" time="1.786">
    <skipped/>
  </testcase> <!-- OrderHistoryTest -->
</testsuite> <!-- SeleniumPractice.SeleniumFrameworkDesign.StandAloneTest2 -->
